### ISSUE TITLE
License

### ISSUE THREAD

**Issue by itsausting** [psiegman/bookmark-generator#5]
Hi!

I found your project and thought it was really neat/convenient.

Would you be interested in adding an explicit license to the project so that it is clear what use is acceptable?

Thanks regardless! 👍

**Comment by psiegman** [comment]
Hi @austinlg96 ,

Does MIT license work for you ?
https://choosealicense.com/licenses/mit/

regards,

Paul

**Comment by itsausting** [comment]
It's your project, not mine! 😄 

I'll comply with whatever you think is appropriate for your work.

I just thought that it might be useful, for example, to provide my new team members a default set of bookmarks when they start.

Thanks so much, whatever you decide!

**Comment by psiegman** [comment]
Done

**Comment by itsausting** [comment]
Thsnks so much!
